version: '3'

services:
  backend:
#    build: server
    image: gcr.io/big-data-arch-youtubed/backend
#    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./server:/backend
    environment:
#      - FLASK_ENV=development
      - FLASK_APP=finTest.py
    ports:
      - "5000:5000"

  frontend:
#    build: client
    image: gcr.io/big-data-arch-youtubed/frontend
#    command: ["npm", "start"]
    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  node-modules: