apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    component: backend
  ports:
  - protocol: TCP
    port: 5000
  type: LoadBalancer
  loadBalancerIP: 34.134.102.218
